sudo: required

services:
  - docker

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - composer lint
  - composer test
