sudo: required

services:
  - docker

language: php

matrix:
  include:
    - php: '7.0'
      env:
        - RUN_STATIC_ANALYSIS="false"

    - php: '7.1'
      env:
        - RUN_STATIC_ANALYSIS="true"

    - php: '7.2'
      env:
        - RUN_STATIC_ANALYSIS="true"

    - php: '7.3'
      env:
        - RUN_STATIC_ANALYSIS="true"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - if [[ ${RUN_STATIC_ANALYSIS} == "true" ]]; then composer require phpstan/phpstan; fi

script:
  - composer lint
  - composer test
  - if [[ ${RUN_STATIC_ANALYSIS} == "true" ]]; then composer static-check; fi
